// lib/words.ts — 200+ pasangan kata yang SANGAT MIRIP

export type WordPair = {
  civilian: string;
  undercover: string;
  category: string;
};

export const WORD_PAIRS: WordPair[] = [
  // ☕ Minuman
  { civilian: 'Kopi', undercover: 'Teh', category: 'Minuman' },
  { civilian: 'Kopi Hitam', undercover: 'Kopi Susu', category: 'Minuman' },
  { civilian: 'Cappuccino', undercover: 'Latte', category: 'Minuman' },
  { civilian: 'Espresso', undercover: 'Americano', category: 'Minuman' },
  { civilian: 'Teh Manis', undercover: 'Teh Tawar', category: 'Minuman' },
  { civilian: 'Teh Hijau', undercover: 'Teh Hitam', category: 'Minuman' },
  { civilian: 'Jus Jeruk', undercover: 'Jus Mangga', category: 'Minuman' },
  { civilian: 'Jus Alpukat', undercover: 'Jus Jambu', category: 'Minuman' },
  { civilian: 'Susu Sapi', undercover: 'Susu Kambing', category: 'Minuman' },
  { civilian: 'Susu Full Cream', undercover: 'Susu Skim', category: 'Minuman' },
  { civilian: 'Air Mineral', undercover: 'Air Soda', category: 'Minuman' },
  { civilian: 'Es Teh', undercover: 'Es Jeruk', category: 'Minuman' },
  { civilian: 'Boba', undercover: 'Cincau', category: 'Minuman' },
  { civilian: 'Sirup Cocopandan', undercover: 'Sirup Leci', category: 'Minuman' },
  { civilian: 'Yogurt Minum', undercover: 'Lassi', category: 'Minuman' },

  // 🍚 Makanan Nusantara
  { civilian: 'Nasi Goreng', undercover: 'Mie Goreng', category: 'Makanan' },
  { civilian: 'Nasi Putih', undercover: 'Nasi Merah', category: 'Makanan' },
  { civilian: 'Soto Ayam', undercover: 'Soto Betawi', category: 'Makanan' },
  { civilian: 'Rawon', undercover: 'Semur', category: 'Makanan' },
  { civilian: 'Rendang', undercover: 'Gulai', category: 'Makanan' },
  { civilian: 'Opor Ayam', undercover: 'Opor Bebek', category: 'Makanan' },
  { civilian: 'Sate Ayam', undercover: 'Sate Kambing', category: 'Makanan' },
  { civilian: 'Sate Padang', undercover: 'Sate Maranggi', category: 'Makanan' },
  { civilian: 'Gado-gado', undercover: 'Pecel', category: 'Makanan' },
  { civilian: 'Ketoprak', undercover: 'Lontong Sayur', category: 'Makanan' },
  { civilian: 'Bakso', undercover: 'Pempek', category: 'Makanan' },
  { civilian: 'Bakso Kuah', undercover: 'Bakso Goreng', category: 'Makanan' },
  { civilian: 'Mie Ayam', undercover: 'Mie Baso', category: 'Makanan' },
  { civilian: 'Mie Goreng Biasa', undercover: 'Mie Goreng Jawa', category: 'Makanan' },
  { civilian: 'Nasi Uduk', undercover: 'Nasi Kuning', category: 'Makanan' },
  { civilian: 'Nasi Padang', undercover: 'Nasi Bakar', category: 'Makanan' },
  { civilian: 'Ayam Goreng', undercover: 'Bebek Goreng', category: 'Makanan' },
  { civilian: 'Ayam Bakar', undercover: 'Ikan Bakar', category: 'Makanan' },
  { civilian: 'Tahu Goreng', undercover: 'Tempe Goreng', category: 'Makanan' },
  { civilian: 'Tahu Sumedang', undercover: 'Tahu Pong', category: 'Makanan' },
  { civilian: 'Pepes Ikan', undercover: 'Pepes Tahu', category: 'Makanan' },
  { civilian: 'Martabak Manis', undercover: 'Martabak Telur', category: 'Makanan' },
  { civilian: 'Terang Bulan', undercover: 'Serabi', category: 'Makanan' },
  { civilian: 'Bubur Ayam', undercover: 'Bubur Kacang Hijau', category: 'Makanan' },
  { civilian: 'Lontong', undercover: 'Ketupat', category: 'Makanan' },
  { civilian: 'Kerak Telor', undercover: 'Kue Cucur', category: 'Makanan' },

  // 🍕 Makanan Western / Modern
  { civilian: 'Pizza', undercover: 'Calzone', category: 'Makanan' },
  { civilian: 'Burger', undercover: 'Sandwich', category: 'Makanan' },
  { civilian: 'Hot Dog', undercover: 'Corn Dog', category: 'Makanan' },
  { civilian: 'Spaghetti', undercover: 'Fettuccine', category: 'Makanan' },
  { civilian: 'Pasta Carbonara', undercover: 'Pasta Bolognese', category: 'Makanan' },
  { civilian: 'Steak Sapi', undercover: 'Steak Kambing', category: 'Makanan' },
  { civilian: 'Fried Chicken', undercover: 'Grilled Chicken', category: 'Makanan' },
  { civilian: 'French Fries', undercover: 'Onion Rings', category: 'Makanan' },
  { civilian: 'Donat', undercover: 'Bagel', category: 'Makanan' },
  { civilian: 'Croissant', undercover: 'Danish', category: 'Makanan' },
  { civilian: 'Waffle', undercover: 'Pancake', category: 'Makanan' },

  // 🍣 Makanan Asia
  { civilian: 'Sushi', undercover: 'Sashimi', category: 'Makanan' },
  { civilian: 'Ramen', undercover: 'Udon', category: 'Makanan' },
  { civilian: 'Takoyaki', undercover: 'Okonomiyaki', category: 'Makanan' },
  { civilian: 'Dim Sum', undercover: 'Siomay', category: 'Makanan' },
  { civilian: 'Bao', undercover: 'Gyoza', category: 'Makanan' },
  { civilian: 'Pho', undercover: 'Tom Yum', category: 'Makanan' },
  { civilian: 'Pad Thai', undercover: 'Khao Pad', category: 'Makanan' },
  { civilian: 'Kimchi', undercover: 'Acar', category: 'Makanan' },
  { civilian: 'Bibimbap', undercover: 'Dolsot', category: 'Makanan' },

  // 🍰 Dessert / Jajanan
  { civilian: 'Es Krim Coklat', undercover: 'Es Krim Vanilla', category: 'Dessert' },
  { civilian: 'Es Krim Cone', undercover: 'Es Krim Cup', category: 'Dessert' },
  { civilian: 'Sorbet', undercover: 'Gelato', category: 'Dessert' },
  { civilian: 'Brownies', undercover: 'Lava Cake', category: 'Dessert' },
  { civilian: 'Cheesecake', undercover: 'Tiramisu', category: 'Dessert' },
  { civilian: 'Kue Lapis', undercover: 'Kue Pelangi', category: 'Dessert' },
  { civilian: 'Onde-onde', undercover: 'Klepon', category: 'Dessert' },
  { civilian: 'Lupis', undercover: 'Cenil', category: 'Dessert' },
  { civilian: 'Es Campur', undercover: 'Es Cendol', category: 'Dessert' },
  { civilian: 'Es Pisang Ijo', undercover: 'Es Teler', category: 'Dessert' },
  { civilian: 'Kolak Pisang', undercover: 'Kolak Ubi', category: 'Dessert' },
  { civilian: 'Puding Coklat', undercover: 'Puding Susu', category: 'Dessert' },
  { civilian: 'Bolu', undercover: 'Muffin', category: 'Dessert' },
  { civilian: 'Kue Bolu Kukus', undercover: 'Kue Bolu Panggang', category: 'Dessert' },

  // 🐾 Hewan Peliharaan / Dekat
  { civilian: 'Kucing', undercover: 'Anjing', category: 'Hewan' },
  { civilian: 'Kucing Anggora', undercover: 'Kucing Persia', category: 'Hewan' },
  { civilian: 'Anjing Herder', undercover: 'Anjing Husky', category: 'Hewan' },
  { civilian: 'Kelinci', undercover: 'Hamster', category: 'Hewan' },
  { civilian: 'Marmut', undercover: 'Chinchilla', category: 'Hewan' },
  { civilian: 'Burung Kenari', undercover: 'Burung Lovebird', category: 'Hewan' },
  { civilian: 'Burung Merpati', undercover: 'Burung Dara', category: 'Hewan' },
  { civilian: 'Ikan Mas', undercover: 'Ikan Koi', category: 'Hewan' },
  { civilian: 'Ikan Cupang', undercover: 'Ikan Guppy', category: 'Hewan' },

  // 🦁 Hewan Liar
  { civilian: 'Singa', undercover: 'Harimau', category: 'Hewan' },
  { civilian: 'Macan Tutul', undercover: 'Cheetah', category: 'Hewan' },
  { civilian: 'Gajah', undercover: 'Badak', category: 'Hewan' },
  { civilian: 'Gorila', undercover: 'Orangutan', category: 'Hewan' },
  { civilian: 'Simpanse', undercover: 'Bonobo', category: 'Hewan' },
  { civilian: 'Serigala', undercover: 'Rubah', category: 'Hewan' },
  { civilian: 'Beruang Grizzly', undercover: 'Beruang Kutub', category: 'Hewan' },
  { civilian: 'Kuda', undercover: 'Zebra', category: 'Hewan' },
  { civilian: 'Sapi', undercover: 'Kerbau', category: 'Hewan' },
  { civilian: 'Ayam', undercover: 'Bebek', category: 'Hewan' },
  { civilian: 'Kambing', undercover: 'Domba', category: 'Hewan' },
  { civilian: 'Babi Hutan', undercover: 'Tapir', category: 'Hewan' },
  { civilian: 'Lumba-lumba', undercover: 'Paus', category: 'Hewan' },
  { civilian: 'Hiu', undercover: 'Pari Manta', category: 'Hewan' },
  { civilian: 'Buaya', undercover: 'Aligator', category: 'Hewan' },
  { civilian: 'Kura-kura', undercover: 'Penyu', category: 'Hewan' },
  { civilian: 'Ular Kobra', undercover: 'Ular Piton', category: 'Hewan' },
  { civilian: 'Elang', undercover: 'Rajawali', category: 'Hewan' },
  { civilian: 'Burung Hantu', undercover: 'Kakatua', category: 'Hewan' },
  { civilian: 'Pinguin', undercover: 'Albatros', category: 'Hewan' },
  { civilian: 'Lebah', undercover: 'Tawon', category: 'Hewan' },
  { civilian: 'Kupu-kupu', undercover: 'Ngengat', category: 'Hewan' },

  // 💼 Profesi
  { civilian: 'Dokter Umum', undercover: 'Dokter Spesialis', category: 'Profesi' },
  { civilian: 'Dokter', undercover: 'Perawat', category: 'Profesi' },
  { civilian: 'Dokter Gigi', undercover: 'Orthodontis', category: 'Profesi' },
  { civilian: 'Guru SD', undercover: 'Guru SMP', category: 'Profesi' },
  { civilian: 'Guru', undercover: 'Dosen', category: 'Profesi' },
  { civilian: 'Pilot', undercover: 'Kopilot', category: 'Profesi' },
  { civilian: 'Pramugari', undercover: 'Pramugara', category: 'Profesi' },
  { civilian: 'Polisi', undercover: 'TNI', category: 'Profesi' },
  { civilian: 'Polisi Lalu Lintas', undercover: 'Satpol PP', category: 'Profesi' },
  { civilian: 'Chef', undercover: 'Sous Chef', category: 'Profesi' },
  { civilian: 'Barista', undercover: 'Bartender', category: 'Profesi' },
  { civilian: 'Programmer', undercover: 'Data Scientist', category: 'Profesi' },
  { civilian: 'Frontend Developer', undercover: 'Backend Developer', category: 'Profesi' },
  { civilian: 'Arsitek', undercover: 'Desainer Interior', category: 'Profesi' },
  { civilian: 'Wartawan', undercover: 'Fotografer', category: 'Profesi' },
  { civilian: 'Hakim', undercover: 'Pengacara', category: 'Profesi' },
  { civilian: 'Notaris', undercover: 'Pengacara', category: 'Profesi' },
  { civilian: 'Aktor', undercover: 'Sutradara', category: 'Profesi' },
  { civilian: 'Penyanyi', undercover: 'Musisi', category: 'Profesi' },
  { civilian: 'Penyanyi Solo', undercover: 'Penyanyi Grup', category: 'Profesi' },
  { civilian: 'Petani', undercover: 'Peternak', category: 'Profesi' },
  { civilian: 'Nelayan', undercover: 'Penyelam', category: 'Profesi' },
  { civilian: 'Astronot', undercover: 'Ilmuwan Roket', category: 'Profesi' },
  { civilian: 'Psikolog', undercover: 'Psikiater', category: 'Profesi' },
  { civilian: 'Akuntan', undercover: 'Auditor', category: 'Profesi' },
  { civilian: 'Manajer', undercover: 'Supervisor', category: 'Profesi' },

  // 📱 Teknologi & Gadget
  { civilian: 'Laptop', undercover: 'Komputer', category: 'Teknologi' },
  { civilian: 'Laptop Gaming', undercover: 'Laptop Biasa', category: 'Teknologi' },
  { civilian: 'iPhone', undercover: 'Samsung Galaxy', category: 'Teknologi' },
  { civilian: 'Smartphone', undercover: 'Tablet', category: 'Teknologi' },
  { civilian: 'iPad', undercover: 'Android Tablet', category: 'Teknologi' },
  { civilian: 'Headphone', undercover: 'Earphone', category: 'Teknologi' },
  { civilian: 'TWS', undercover: 'Earphone Kabel', category: 'Teknologi' },
  { civilian: 'Keyboard Mechanical', undercover: 'Keyboard Membrane', category: 'Teknologi' },
  { civilian: 'Mouse Gaming', undercover: 'Mouse Biasa', category: 'Teknologi' },
  { civilian: 'Printer Laser', undercover: 'Printer Inkjet', category: 'Teknologi' },
  { civilian: 'Kamera DSLR', undercover: 'Kamera Mirrorless', category: 'Teknologi' },
  { civilian: 'Smartwatch', undercover: 'Fitness Tracker', category: 'Teknologi' },
  { civilian: 'Apple Watch', undercover: 'Galaxy Watch', category: 'Teknologi' },
  { civilian: 'TV LED', undercover: 'TV OLED', category: 'Teknologi' },
  { civilian: 'Proyektor', undercover: 'Layar LED', category: 'Teknologi' },
  { civilian: 'Power Bank', undercover: 'Charger Portabel', category: 'Teknologi' },
  { civilian: 'Speaker Bluetooth', undercover: 'Speaker Kabel', category: 'Teknologi' },
  { civilian: 'Router WiFi', undercover: 'Modem', category: 'Teknologi' },
  { civilian: 'SSD', undercover: 'HDD', category: 'Teknologi' },
  { civilian: 'USB-C', undercover: 'Micro USB', category: 'Teknologi' },
  { civilian: 'PS5', undercover: 'Xbox Series X', category: 'Teknologi' },
  { civilian: 'Nintendo Switch', undercover: 'Steam Deck', category: 'Teknologi' },
  { civilian: 'VR Headset', undercover: 'AR Glasses', category: 'Teknologi' },
  { civilian: 'Drone', undercover: 'Helikopter RC', category: 'Teknologi' },

  // 🔧 Benda Sehari-hari
  { civilian: 'Pensil', undercover: 'Pulpen', category: 'Benda' },
  { civilian: 'Pulpen Biasa', undercover: 'Pulpen Gel', category: 'Benda' },
  { civilian: 'Buku Tulis', undercover: 'Buku Gambar', category: 'Benda' },
  { civilian: 'Kursi Kayu', undercover: 'Kursi Plastik', category: 'Benda' },
  { civilian: 'Sofa', undercover: 'Kursi Malas', category: 'Benda' },
  { civilian: 'Meja Makan', undercover: 'Meja Kerja', category: 'Benda' },
  { civilian: 'Lemari Baju', undercover: 'Lemari Buku', category: 'Benda' },
  { civilian: 'Kasur Busa', undercover: 'Kasur Spring Bed', category: 'Benda' },
  { civilian: 'Bantal', undercover: 'Guling', category: 'Benda' },
  { civilian: 'Selimut', undercover: 'Sprei', category: 'Benda' },
  { civilian: 'Lampu LED', undercover: 'Lampu Bohlam', category: 'Benda' },
  { civilian: 'Lilin', undercover: 'Obor', category: 'Benda' },
  { civilian: 'Cermin', undercover: 'Kaca', category: 'Benda' },
  { civilian: 'Kunci Rumah', undercover: 'Gembok', category: 'Benda' },
  { civilian: 'Pisau Dapur', undercover: 'Gunting', category: 'Benda' },
  { civilian: 'Sendok', undercover: 'Garpu', category: 'Benda' },
  { civilian: 'Sumpit', undercover: 'Garpu', category: 'Benda' },
  { civilian: 'Piring', undercover: 'Mangkuk', category: 'Benda' },
  { civilian: 'Gelas Plastik', undercover: 'Gelas Kaca', category: 'Benda' },
  { civilian: 'Cangkir', undercover: 'Mug', category: 'Benda' },
  { civilian: 'Termos', undercover: 'Botol Minum', category: 'Benda' },
  { civilian: 'Sapu', undercover: 'Pel', category: 'Benda' },
  { civilian: 'Payung', undercover: 'Jas Hujan', category: 'Benda' },
  { civilian: 'Tas Tangan', undercover: 'Ransel', category: 'Benda' },
  { civilian: 'Koper', undercover: 'Tas Travelling', category: 'Benda' },
  { civilian: 'Sepatu Sneakers', undercover: 'Sepatu Boots', category: 'Benda' },
  { civilian: 'Sandal Jepit', undercover: 'Sandal Selop', category: 'Benda' },
  { civilian: 'Jam Tangan', undercover: 'Jam Dinding', category: 'Benda' },
  { civilian: 'Kipas Angin', undercover: 'AC', category: 'Benda' },
  { civilian: 'Kulkas', undercover: 'Freezer', category: 'Benda' },
  { civilian: 'Kompor Gas', undercover: 'Kompor Listrik', category: 'Benda' },
  { civilian: 'Microwave', undercover: 'Oven', category: 'Benda' },
  { civilian: 'Blender', undercover: 'Food Processor', category: 'Benda' },
  { civilian: 'Rice Cooker', undercover: 'Magic Com', category: 'Benda' },
  { civilian: 'Setrika', undercover: 'Steamer Baju', category: 'Benda' },
  { civilian: 'Mesin Cuci', undercover: 'Pengering Baju', category: 'Benda' },
  { civilian: 'Vacuum Cleaner', undercover: 'Sapu Robot', category: 'Benda' },

  // 🚗 Kendaraan
  { civilian: 'Mobil', undercover: 'Motor', category: 'Kendaraan' },
  { civilian: 'Mobil Listrik', undercover: 'Mobil Hybrid', category: 'Kendaraan' },
  { civilian: 'Motor Matic', undercover: 'Motor Manual', category: 'Kendaraan' },
  { civilian: 'Bus Kota', undercover: 'Minibus', category: 'Kendaraan' },
  { civilian: 'Bus AC', undercover: 'Bus Biasa', category: 'Kendaraan' },
  { civilian: 'Kereta Cepat', undercover: 'Kereta Biasa', category: 'Kendaraan' },
  { civilian: 'MRT', undercover: 'LRT', category: 'Kendaraan' },
  { civilian: 'Pesawat', undercover: 'Helikopter', category: 'Kendaraan' },
  { civilian: 'Pesawat Komersial', undercover: 'Pesawat Pribadi', category: 'Kendaraan' },
  { civilian: 'Kapal Feri', undercover: 'Kapal Pesiar', category: 'Kendaraan' },
  { civilian: 'Speedboat', undercover: 'Kapal Layar', category: 'Kendaraan' },
  { civilian: 'Sepeda Biasa', undercover: 'Sepeda Listrik', category: 'Kendaraan' },
  { civilian: 'Sepeda Gunung', undercover: 'Sepeda Lipat', category: 'Kendaraan' },
  { civilian: 'Truk', undercover: 'Pickup', category: 'Kendaraan' },
  { civilian: 'Ambulans', undercover: 'Mobil Pemadam', category: 'Kendaraan' },
  { civilian: 'Ojek', undercover: 'Taksi', category: 'Kendaraan' },

  // 🌍 Tempat
  { civilian: 'Pantai', undercover: 'Danau', category: 'Tempat' },
  { civilian: 'Pantai Pasir Putih', undercover: 'Pantai Pasir Hitam', category: 'Tempat' },
  { civilian: 'Gunung', undercover: 'Bukit', category: 'Tempat' },
  { civilian: 'Hutan', undercover: 'Hutan Mangrove', category: 'Tempat' },
  { civilian: 'Gurun', undercover: 'Padang Savana', category: 'Tempat' },
  { civilian: 'Mall', undercover: 'Pasar Modern', category: 'Tempat' },
  { civilian: 'Pasar Tradisional', undercover: 'Pasar Malam', category: 'Tempat' },
  { civilian: 'Museum Sejarah', undercover: 'Museum Seni', category: 'Tempat' },
  { civilian: 'Bioskop', undercover: 'Teater', category: 'Tempat' },
  { civilian: 'Bioskop Reguler', undercover: 'Bioskop 4DX', category: 'Tempat' },
  { civilian: 'Rumah Sakit', undercover: 'Klinik', category: 'Tempat' },
  { civilian: 'Puskesmas', undercover: 'Klinik', category: 'Tempat' },
  { civilian: 'SD', undercover: 'SMP', category: 'Tempat' },
  { civilian: 'SMA', undercover: 'SMK', category: 'Tempat' },
  { civilian: 'Universitas Negeri', undercover: 'Universitas Swasta', category: 'Tempat' },
  { civilian: 'Bandara', undercover: 'Pelabuhan', category: 'Tempat' },
  { civilian: 'Stasiun Kereta', undercover: 'Terminal Bus', category: 'Tempat' },
  { civilian: 'Hotel Bintang 5', undercover: 'Hotel Bintang 3', category: 'Tempat' },
  { civilian: 'Hostel', undercover: 'Guest House', category: 'Tempat' },
  { civilian: 'Masjid', undercover: 'Mushola', category: 'Tempat' },
  { civilian: 'Gereja', undercover: 'Kapel', category: 'Tempat' },
  { civilian: 'Taman Kota', undercover: 'Taman Bermain', category: 'Tempat' },
  { civilian: 'Kebun Binatang', undercover: 'Taman Safari', category: 'Tempat' },
  { civilian: 'Lapangan Sepak Bola', undercover: 'Lapangan Futsal', category: 'Tempat' },
  { civilian: 'Gym', undercover: 'Kolam Renang', category: 'Tempat' },
  { civilian: 'Warung', undercover: 'Kantin', category: 'Tempat' },
  { civilian: 'Restoran', undercover: 'Kafe', category: 'Tempat' },
  { civilian: 'Apotek', undercover: 'Toko Obat Herbal', category: 'Tempat' },
  { civilian: 'Minimarket', undercover: 'Supermarket', category: 'Tempat' },
  { civilian: 'Toko Buku', undercover: 'Perpustakaan', category: 'Tempat' },

  // ⚽ Olahraga
  { civilian: 'Sepak Bola', undercover: 'Futsal', category: 'Olahraga' },
  { civilian: 'Basket', undercover: 'Voli', category: 'Olahraga' },
  { civilian: 'Tenis', undercover: 'Badminton', category: 'Olahraga' },
  { civilian: 'Renang Gaya Bebas', undercover: 'Renang Gaya Dada', category: 'Olahraga' },
  { civilian: 'Lari Sprint', undercover: 'Lari Maraton', category: 'Olahraga' },
  { civilian: 'Bulu Tangkis', undercover: 'Squash', category: 'Olahraga' },
  { civilian: 'Golf', undercover: 'Kriket', category: 'Olahraga' },
  { civilian: 'Tinju', undercover: 'MMA', category: 'Olahraga' },
  { civilian: 'Karate', undercover: 'Taekwondo', category: 'Olahraga' },
  { civilian: 'Yoga', undercover: 'Pilates', category: 'Olahraga' },
  { civilian: 'Skateboard', undercover: 'Inline Skate', category: 'Olahraga' },
  { civilian: 'Panjat Tebing', undercover: 'Bouldering', category: 'Olahraga' },
  { civilian: 'Surfing', undercover: 'Wakeboarding', category: 'Olahraga' },
  { civilian: 'Ski', undercover: 'Snowboard', category: 'Olahraga' },
  { civilian: 'Bersepeda Gunung', undercover: 'Bersepeda Jalan', category: 'Olahraga' },

  // 👗 Pakaian
  { civilian: 'Kaos', undercover: 'Polo Shirt', category: 'Pakaian' },
  { civilian: 'Kemeja', undercover: 'Blouse', category: 'Pakaian' },
  { civilian: 'Celana Jeans', undercover: 'Celana Chino', category: 'Pakaian' },
  { civilian: 'Rok Mini', undercover: 'Rok Midi', category: 'Pakaian' },
  { civilian: 'Gaun', undercover: 'Jumpsuit', category: 'Pakaian' },
  { civilian: 'Jaket Denim', undercover: 'Jaket Kulit', category: 'Pakaian' },
  { civilian: 'Hoodie', undercover: 'Sweater', category: 'Pakaian' },
  { civilian: 'Jas', undercover: 'Blazer', category: 'Pakaian' },
  { civilian: 'Baju Batik', undercover: 'Baju Tenun', category: 'Pakaian' },
  { civilian: 'Sarung', undercover: 'Kain Kebaya', category: 'Pakaian' },
  { civilian: 'Topi Baseball', undercover: 'Topi Fedora', category: 'Pakaian' },
  { civilian: 'Kacamata Baca', undercover: 'Kacamata Minus', category: 'Pakaian' },

  // 🎮 Hiburan
  { civilian: 'Netflix', undercover: 'Disney+', category: 'Hiburan' },
  { civilian: 'YouTube', undercover: 'TikTok', category: 'Hiburan' },
  { civilian: 'Spotify', undercover: 'Apple Music', category: 'Hiburan' },
  { civilian: 'Instagram', undercover: 'Twitter/X', category: 'Hiburan' },
  { civilian: 'WhatsApp', undercover: 'Telegram', category: 'Hiburan' },
  { civilian: 'Mobile Legends', undercover: 'Free Fire', category: 'Hiburan' },
  { civilian: 'Minecraft', undercover: 'Roblox', category: 'Hiburan' },
  { civilian: 'GTA V', undercover: 'Red Dead Redemption', category: 'Hiburan' },
  { civilian: 'Film Action', undercover: 'Film Thriller', category: 'Hiburan' },
  { civilian: 'Film Horor', undercover: 'Film Misteri', category: 'Hiburan' },
  { civilian: 'Novel', undercover: 'Komik', category: 'Hiburan' },
  { civilian: 'Anime', undercover: 'Kartun', category: 'Hiburan' },
  { civilian: 'Konser Musik', undercover: 'Festival Musik', category: 'Hiburan' },
];

export function getRandomWordPair(usedIndices: Set<number>): { pair: WordPair; index: number } {
  const available = WORD_PAIRS.map((_, i) => i).filter((i) => !usedIndices.has(i));
  if (available.length === 0) {
    const index = Math.floor(Math.random() * WORD_PAIRS.length);
    return { pair: WORD_PAIRS[index], index };
  }
  const randomIdx = available[Math.floor(Math.random() * available.length)];
  return { pair: WORD_PAIRS[randomIdx], index: randomIdx };
}

export function shuffleArray<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
